application:
 build: ./
 volumes:
  - "application:/docker-node/application"
 environment:
  REDIS_IP: 192.168.59.103
 ports:
  - "80:3000"
 hostname: formtitan
 domainname: formtitan.org
 links:
  - redis
redis:
 build: ./redis
 ports:
  - "6379:6379"


